version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: make tests
  tools-tests:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run:
          name: "Run tools test"
          command: make -C tools test

  tools-build:
    docker:
      - image: cimg/go:1.16
    steps:
      - checkout
      - run:
          name: "Run tools build"
          command: make -C tools build

workflows:
  version: 2
  test_and_build:
    jobs:
      - tests
      - tools-tests
      - tools-build:
          requires:
            - tools-tests