#!/usr/bin/env bash

# Usage: Runs gogen for all Go files that have changed between the current code and master.

SCRIPT="$(python -c 'import os, sys; print(os.path.realpath(sys.argv[1]))' "${BASH_SOURCE[0]}")"
source "$(dirname "$SCRIPT")/../../lib/common.sh"

gitroot="$(git rev-parse --show-toplevel)"
[[ $? -eq 0 ]] || die "Current directory is not a git repository."

if [[ -f "${gitroot}/go.mod" ]]; then
	export GO111MODULE=on
fi

# From https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch#comment92366240_50056710
main_branch="$(git remote show origin | grep "HEAD branch" | sed 's/.*: //')"
[[ -n "${main_branch}" ]] || die "Failed to get main branch"

diffbase="$(git merge-base HEAD "origin/${main_branch}")"
[[ $? -eq 0 ]] || die "Failed to determine diffbase"

generated_files="$(git -C "$gitroot" grep -l '^// Code generated by .* DO NOT EDIT\.' -- '*.go' | sed -e "s@^@${gitroot}/@")"

IFS=$'\n' read -d '' -r -a changed_files < <(
	{
		git diff "$diffbase" --name-status . |
		sed -n -E -e "s@^[AM][[:space:]]+|^R[^[:space:]]*[[:space:]]+[^[:space:]]+[[:space:]]+@${gitroot}/@p" ;
		echo "$generated_files" ; echo "$generated_files"
} | sort | uniq -u) || true

function private_gogen() {
	local status=0
	local changed_files=("$@")
	local gofiles

	IFS=$'\n' read -d '' -r -a gofiles < <(
		printf '%s\n' "${changed_files[@]}" |
		grep '\.go$'
  )
  [[ "${#gofiles[@]}" == 0 ]] && return 0

  IFS=$'\n' read -d '' -r -a godirs < <(
		for f in "${gofiles[@]}"; do dirname "$f"; done |
    sort | uniq)

	einfo "Running go generate..."
	for dir in "${godirs[@]}"; do
	  einfo "  Generating for ${dir}..."
    ( cd "$dir" && go generate "./" ) && (( status == 0 ))
    status=$?
	done

	return "${status}"
}

[[ "${#changed_files[@]}" -eq 0 ]] && { ewarn "No relevant changes found in current directory."; exit 0; }

status=0

private_gogen "${changed_files[@]}" && (( status == 0 ))
status=$?

[[ "${status}" -eq 0 ]] && exit 0
efatal "An error occurred while generating files"
exit 1